Update fee calc to use CLSAG + other minor changes
mymonero/mymonero-core-cpp pull request #35
Opened 2022-02-28 07:57 UTC by j-berman

Matches wallet2 fee calculations

2022-02-28 21:06 UTC, paulshapiro commented
Yeah, again, I'm confused why this upgrade was not made sooner with CLSAG txs, guess they missed it, but these changes are correct. Thanks for doing this.

Fwiw these functions are probably the most basic example of what we're brewing in PRs to mainline to factor out of wallet2 so code can be converged.

2022-03-09 14:03 UTC, devinpearson requested changes

2022-03-09 14:03 UTC, devinpearson commented on src/monero_transfer_utils.cpp
> +		// use a minimum viabale estimate_fee() with 1 input. It would be better to under-shoot this estimate, and then need to use a higher fee  from calculate_fee() because the estimate is too low,
looks to be a small spelling mistake in viable. Should it read "use a minimum viable estimate_fee()"

2022-03-09 14:03 UTC, devinpearson commented on README.md
> +	* `clsag: BooLString`
small typo. there is a capital L in your addition of BoolString

2022-07-14 10:14 UTC, merged